### ISSUE TITLE
java-sdk tests are failing

### ISSUE THREAD

**Issue by j-pas** [guardtime/ksi-sdk-samples#8]
Hi Guardtime,

It seems like the examples in the java-sdk are no longer passing the maven tests. 

When running the "mvn test" with the endpoints provided by the KSI Developer guide (https://docs.guardtime.net/ksi-dev-guide/#IntegrationResources) then the signing examples are returning  "Response error 257: KSIv1 is deprecated"

Any feedback would be appreciated!

Kind regards,
Jan-Willem

**Comment by margoraja** [comment]
Hi Jan-Willem,

Samples have not been updated yet and thus are using older java sdk. Change used java sdk version to 4.11.153. Also I noticed that samples are using older publications file, I recommend to use "-Dpublications.file.url={publications url}" to over come that as well.

Updated will follow shortly.

**Comment by j-pas** [comment]
That seems to have solved the issue, thanks!
